# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.76591972 0.33472877 0.21185608]
  [0.8170363  0.20424699 0.95396424]
  [0.45340072 0.37089093 0.84571468]]

 [[0.99635003 0.87404906 0.95740367]
  [0.00981052 0.38321547 0.37574438]
  [0.91909653 0.56468606 0.44370147]]

 [[0.0127814  0.39028372 0.70264534]
  [0.90071663 0.7939434  0.53699215]
  [0.6091891  0.26755158 0.07247876]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
import numpy as np
x = np.diag([1, 2, 3, 4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [6]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.3198678  0.00672239 0.10241158 0.22369772 0.27661512]
 [0.79353111 0.66365838 0.05794905 0.13456986 0.43813569]
 [0.90332405 0.49723959 0.25613005 0.04713796 0.88294131]
 [0.60099409 0.12726437 0.17158786 0.98140244 0.08793493]
 [0.71789413 0.00724131 0.86353204 0.69227043 0.01140382]]
After normalization:
[[3.21280204e-01 0.00000000e+00 9.81749710e-02 2.22611850e-01
  2.76903925e-01]
 [8.07248201e-01 6.74001677e-01 5.25574083e-02 1.31168653e-01
  4.42620422e-01]
 [9.19893312e-01 5.03259711e-01 2.55886699e-01 4.14654668e-02
  8.98981079e-01]
 [6.09709515e-01 1.23673384e-01 1.69148293e-01 1.00000000e+00
  8.33222470e-02]
 [7.29646350e-01 5.32395606e-04 8.79067600e-01 7.03357001e-01
  4.80303707e-03]]


# 5.  How to find common values between two arrays?

In [7]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [8]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [9]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 0 1 0 0 1]
Second array:
[1 0 0 1 1 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [10]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.83803843 0.50286797 0.85595991 0.77696678 0.38962578 0.45687835
 0.20565567 0.45157525 0.32836749 0.43727425]
Maximum value replaced by 0:
[0.83803843 0.50286797 0.         0.77696678 0.38962578 0.45687835
 0.20565567 0.45157525 0.32836749 0.43727425]


# 9. How to print all the values of an array?

In [18]:
arr = [1, 2, 3, 4, 5];     
     
print("Elements of given array: ");    
#Loop through the array by incrementing the value of i     
    
for i in range(0, len(arr)):    
    print(arr[i]),  

Elements of given array: 
1
2
3
4
5


# 10.Subtract the mean of each row of a matrix

In [13]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.29787381 0.33901843 0.87987882 0.0627094  0.64593052 0.14162674
  0.13647147 0.88243583 0.90171867 0.84790437]
 [0.78960721 0.32230691 0.97715957 0.4507872  0.24759765 0.10987192
  0.51953505 0.17727194 0.86758752 0.22671868]
 [0.94581264 0.5841386  0.48454184 0.69582642 0.19754696 0.52360523
  0.03785322 0.27020054 0.45260883 0.28679484]
 [0.85754188 0.91798526 0.79516337 0.78554259 0.11274907 0.19819719
  0.61055866 0.7700434  0.83915489 0.11172617]
 [0.93012291 0.35188887 0.67073453 0.31009535 0.33645533 0.46550866
  0.08754895 0.81758035 0.1894598  0.12233525]]

Subtract the mean of each row of the said matrix:

[[-0.21568299 -0.17453838  0.36632201 -0.45084741  0.13237371 -0.37193007
  -0.37708533  0.36887902  0.38816187  0.33434756]
 [ 0.32076284 -0.14653745  0.5083152  -0.01805716 -0.22124671 -0.35897244
   0.05069069 -0.29157243  0.39874315 -0.24212569]
 [ 0.49791973  0.13624569  0.03664893  0.2479335  -0.25034595  0.07571232
  -0.4100397  -0.17769237  0.0

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

# 13.How to find the most frequent value in an array?

In [17]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[8 8 8 7 6 0 5 8 4 6 2 3 5 4 1 8 4 6 9 9 6 5 7 7 6 5 3 0 5 7 4 5 4 9 4 3 8
 3 0 7]
Most frequent value in the above array:
4


# 14.How to get the n largest values of an array

In [20]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [14]:
import numpy as np
arra1 = np.array([("Yasemin Rayner", 88.5, 90),
                 ("Ayaana Mcnamara", 87, 99),
             ("Jody Preece", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Yasemin Rayner' '88.5' '90']
 ['Ayaana Mcnamara' '87' '99']
 ['Jody Preece' '85.5' '91']]

Record array;
[(b'Yasemin Rayner', 88.5, 90) (b'Ayaana Mcnamara', 87. , 99)
 (b'Jody Preece', 85.5, 91)]
